packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - electron
  - esbuild
  - '@swc/core'
  - 'better-sqlite3'

catalogs:
  node:
    '@types/node': '^22.13.13'

  vite:
    'vite': '^6.2.3'

  tailwind:
    'tailwindcss': '^4.1.5'
    '@tailwindcss/forms': '^0.5.10'
    '@tailwindcss/typography': '^0.5.16'
    '@tailwindcss/vite': '^4.1.5'
    'tailwind-merge': '^3.2.0'

  react:
    'react': '19.0.0'
    'react-dom': '19.0.0'
    '@types/react': '19.1.3'
    '@types/react-dom': '19.0.4'

  icons:
    'lucide-react': '0.507.0'

  hookform:
    'react-hook-form': '7.55.0'
    '@hookform/resolvers': '5.0.1'

  drizzle:
    'drizzle-orm': '0.43.1'
    'drizzle-kit': '0.31.0'

  sqlite:
    'better-sqlite3': '11.9.1'
    '@types/better-sqlite3': '7.6.13'

  utils:
    'zod': '3.24.2'
    'i18next': '25.0.1'
    'zod-i18n-map': '2.27.0'
    'zustand': '5.0.3'

  prettier:
    'prettier': '^3.5.3'
    'prettier-plugin-astro': '^0.14.1'
    'prettier-plugin-tailwindcss': '^0.6.11'
