// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	CommonWords: {
		/**
		 * C​o​n​t​i​n​u​e
		 */
		Continue: string
		/**
		 * U​p​d​a​t​e
		 */
		Update: string
	}
	FormLocalRegister: {
		/**
		 * P​u​b​l​i​c​ ​n​a​m​e
		 */
		Label: string
		/**
		 * H​o​w​ ​o​t​h​e​r​s​ ​w​i​l​l​ ​s​e​e​ ​y​o​u
		 */
		Hint: string
		/**
		 * e​x​:​ ​D​a​n​i​e​l​ ​P​.​ ​B​e​c​e​r​r​a
		 */
		Placeholder: string
	}
	Dashboard: {
		PageEmitter: {
			/**
			 * C​a​l​l
			 */
			Title: string
			/**
			 * H​e​l​p​!
			 */
			MainButton: string
			/**
			 * P​e​o​p​l​e​ ​w​a​i​t​i​n​g​ ​y​o​u​:
			 */
			ListenersLabel: string
			/**
			 * A​l​l​o​w​ ​o​t​h​e​r​s​ ​t​o​ ​d​e​t​e​c​t​ ​t​h​i​s​ ​d​e​v​i​c​e
			 */
			EnableDetectionCheckbox: string
		}
		PageReceiver: {
			/**
			 * L​i​s​t​s
			 */
			Title: string
			SelectedDevicesTab: {
				/**
				 * K​n​o​w​n​ ​d​e​v​i​c​e​s
				 */
				Title: string
				/**
				 * N​o​ ​k​n​o​w​n​ ​d​e​v​i​c​e​s
				 */
				EmptyPlaceholder: string
			}
			SearchDevicesTab: {
				/**
				 * D​i​s​c​o​v​e​r
				 */
				Title: string
				/**
				 * D​e​t​e​c​t​ ​d​e​v​i​c​e​s
				 */
				DetectButton: string
				/**
				 * N​o​ ​d​e​v​i​c​e​s​ ​n​e​a​r​b​y
				 */
				EmptyPlaceholder: string
			}
		}
		PageSettings: {
			/**
			 * S​e​t​t​i​n​g​s
			 */
			Title: string
			FormLocalName: {
				/**
				 * C​u​r​r​e​n​t​ ​n​a​m​e
				 */
				Label: string
				/**
				 * C​h​a​n​g​e​s​ ​w​i​l​l​ ​b​e​ ​r​e​f​l​e​c​t​e​d​ ​o​n​ ​o​t​h​e​r​ ​p​e​o​p​l​e​'​s​ ​d​e​v​i​c​e​s​.
				 */
				Hint: string
			}
		}
	}
}

export type TranslationFunctions = {
	CommonWords: {
		/**
		 * Continue
		 */
		Continue: () => LocalizedString
		/**
		 * Update
		 */
		Update: () => LocalizedString
	}
	FormLocalRegister: {
		/**
		 * Public name
		 */
		Label: () => LocalizedString
		/**
		 * How others will see you
		 */
		Hint: () => LocalizedString
		/**
		 * ex: Daniel P. Becerra
		 */
		Placeholder: () => LocalizedString
	}
	Dashboard: {
		PageEmitter: {
			/**
			 * Call
			 */
			Title: () => LocalizedString
			/**
			 * Help!
			 */
			MainButton: () => LocalizedString
			/**
			 * People waiting you:
			 */
			ListenersLabel: () => LocalizedString
			/**
			 * Allow others to detect this device
			 */
			EnableDetectionCheckbox: () => LocalizedString
		}
		PageReceiver: {
			/**
			 * Lists
			 */
			Title: () => LocalizedString
			SelectedDevicesTab: {
				/**
				 * Known devices
				 */
				Title: () => LocalizedString
				/**
				 * No known devices
				 */
				EmptyPlaceholder: () => LocalizedString
			}
			SearchDevicesTab: {
				/**
				 * Discover
				 */
				Title: () => LocalizedString
				/**
				 * Detect devices
				 */
				DetectButton: () => LocalizedString
				/**
				 * No devices nearby
				 */
				EmptyPlaceholder: () => LocalizedString
			}
		}
		PageSettings: {
			/**
			 * Settings
			 */
			Title: () => LocalizedString
			FormLocalName: {
				/**
				 * Current name
				 */
				Label: () => LocalizedString
				/**
				 * Changes will be reflected on other people's devices.
				 */
				Hint: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
